### ISSUE TITLE
allow specifying custom directory name

### ISSUE THREAD

**Issue by tony** [tony/vcspull#18]
By default

```yaml

~/path/to/dirs:
  project_name:
    repo: 'git+repo_url'
```

The directory checked out would be ``~/path/to/dirs/project_name``.

Allow overriding the dir, so ``project_name`` could download to ``~/path/to/dirs/custom_dir``

```yaml

~/path/to/dirs:
  project_name:
    dir: custom_dir
    repo: 'git+repo_url'
```
