### ISSUE TITLE
New repo format

### ISSUE THREAD

**Issue by tony** [tony/vcspull#23]
To simplify things, lets make the format verbose.

```yaml
/path/to/parent_dir:
   - name: 'default to vcs default' # optional
   - url: raw_vcs_url # no more ambiguity over how to handle auth # required
   - vcs: 'git' # or 'hg', 'svn' # required
   - prompt_auth: true/false (whether to prompt or skip if not authenticated) # default true
   - rev: afafaf # changeset, revision number or branch, defaults to head
   - username: u # optional
   - password: p # optional
   - externals: True # checkout submodules/svn externals
```
