### ISSUE TITLE
using the same directory doesn't merge repos

### ISSUE THREAD

**Issue by tony** [tony/vcspull#30]
```yaml

~/study/c++/:
  uMario:
    repo: "git+https://github.com/jakowskidev/uMario_Jakowski"
    remotes:
      tony: "git@github.com:tony/uMario_Jakowski.git"

~/study/c++/:
  sdl2-playproject: "git+ssh://git@github.com/tony/sdl2-playproject.git"
  aseprite:
    repo: 'git+https://github.com/aseprite/aseprite.git'
    remotes:
      tony: 'git+ssh://git@github.com/tony/aseprite.git'
```

won't merge repos. fix
